#  NumPy 

Numpy is a linear algebra library for python 

# NumPy arrays 

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list) #casts the list to array 

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
arry = np.array(my_mat)

In [7]:
arry

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10) #

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(0,11,2) #step 2s, thats every next second value 

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3) #will give the output of one row and three columns (all the output will be in 0's)

array([0., 0., 0.])

In [12]:
np.zeros((3,4)) #if we pass in tuple, the first 3 acts as row and  4    acts as column (a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.ones(4) #here the outputs will be in ones and the 1 row and 4 columns 

array([1., 1., 1., 1.])

In [14]:
#linspace will give output of the n number of evenly spaced points between the asked numbers

In [15]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.linspace(0,4,10) 

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [17]:
#np.eye(n) will create n*n diagonal matrix 

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#there is a  method for getting the the random numbers 

In [64]:
np.random.rand(5)

array([0.06460064, 0.96446188, 0.370414  , 0.62681775, 0.95545294])

In [63]:
#for 5*5 matrix

In [65]:
np.random.rand(5,5)

array([[0.44383214, 0.35512842, 0.74844922, 0.58982578, 0.35025765],
       [0.29307422, 0.14408848, 0.11708448, 0.37113371, 0.11576566],
       [0.37484767, 0.27041762, 0.7545567 , 0.0135111 , 0.87923615],
       [0.91237019, 0.05041869, 0.48461442, 0.05634708, 0.26964714],
       [0.80118567, 0.4352448 , 0.05815174, 0.63840758, 0.80362048]])

In [23]:
#If we want a sample or a many samples from standard normal or gaussian  normal ,use randn 

In [24]:
np.random.randn(1)

array([0.63661109])

In [25]:
np.random.randn(2)

array([-0.80449209,  2.2694442 ])

In [26]:
np.random.randn(3)

array([-1.43478445,  1.12566024, -0.01176863])

In [27]:
np.random.randn(4,4)

array([[ 0.98147239, -0.46151707, -1.21955051, -0.54031051],
       [-0.93407368,  0.27548095,  2.02905877,  0.74580101],
       [ 1.13313758, -0.85766643,  0.16082523,  0.72561058],
       [ 1.76850524, -0.31973002, -0.0049591 , -0.07735816]])

In [28]:
#randint : used for getting the random integer from low to high 

In [29]:
np.random.randint(1,100)

93

In [30]:
np.random.randint(1,100,10) #for 10 random integers 

array([21, 29, 93,  1, 32, 88, 94, 33, 87, 14])

In [74]:
arr = np.arange(36)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [45]:
ranarr = np.random.randint(0,50,10)

In [46]:
ranarr

array([22, 46, 27, 33, 32, 32, 20, 14, 30, 36])

In [67]:
arr.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [36]:
ranarr

array([17, 29, 43, 47, 23, 36, 24, 25, 14, 22])

In [37]:
ranarr.max()

47

In [38]:
ranarr.min()

14

In [48]:
#for the index location of max value 
ranarr.argmax()


1

In [47]:
ranarr.argmin()

7

In [50]:
arr.shape #here (25,) denotes one dimensioaal 

(25,)

In [68]:
arr = arr.reshape(6,6)

In [69]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [70]:
arr.shape

(6, 6)

In [71]:
arr.dtype

dtype('int32')

In [73]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])