In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[8]

8

In [9]:
arr[1:4]

array([1, 2, 3])

In [10]:
arr[2:]#return all after 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[:5] #does not include the end required number 

array([0, 1, 2, 3, 4])

In [12]:
arr[0:5] 

array([0, 1, 2, 3, 4])

In [14]:
#we can assign the numbers to perticular place 
#for example , if we need 100 in place if 0 to 5 
arr[0:5] = 100 

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice_of_arr = arr[0:6]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [22]:
slice_of_arr[:] = 99

In [24]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [25]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
#if we want to make whole list to same value 

arr_copy = arr.copy()

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
arr_copy[:] = 100

In [32]:
arr_copy #all these values in arr_copy will be changed but the main arr will be uneffected 

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [33]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

###### Two dimensional arreys  

In [34]:
import numpy as np

In [71]:
#lets write a two dimensional array 
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [72]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr_2d[0][0]  #first 0 represents row and second represents column 

1

The main confusion here is 0 represents the 1st row or column and the 1 represents 2nd row or colunm 

In [43]:
arr_2d[0] #this is the 1st row 

array([1, 2, 3])

In [48]:
arr_2d[1][1]

5

In [49]:
arr_2d[2][1]

8

In [50]:
# instead of using the two square brackets , we can also use only one and this is the recomended 
arr_2d[2,1]

8

In [77]:
#we can also grab a part of matix 
# if i want to grab 5,6,8,9

arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [81]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [82]:
arr_2d[:2,:2] 

array([[1, 2],
       [4, 5]])

In [83]:
arr_2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [94]:
arr = np.arange(1,11)

In [95]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr > 5 # gives false wherever the given value 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])